name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: voidzero-dev/setup-vp@v1
              with:
                  cache: true

            - run: vp dlx playwright install --with-deps chromium

            - run: vp check
            - run: vp build
            - run: vp dlx playwright test
